
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
image: node:10.15.3
pipelines:
  branches:
    develop:
      - step:
          name: Build
          script:
            - npm install
            - npm run build
            - npm run generate
          artifacts:
            - dist/**
      - step:
          name: Deploy
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                #       AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION:  $AWS_DEFAULT_REGION
                #       AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                #       AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
                S3_BUCKET: "cloudenly.com"
                ACL: "public-read"
                LOCAL_PATH: "dist"